### PR TITLE
fix: glibc error when patching on Linux

### LINKED ISSUE #47: fix: `patch` failed for one user on linux
```
Exception: Failed to create diff: /home/user/shorebird/bin/cache/artifacts/patch/patch: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.33' not found (required by /home/user.shorebird/bin/cache/artifacts/patch/patch)
/home/user/.shorebird/bin/cache/artifacts/patch/patch: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.32' not found (required by /home/user/.shorebird/bin/cache/artifacts/patch/patch)
/home/user/.shorebird/bin/cache/artifacts/patch/patch: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/user/.shorebird/bin/cache/artifacts/patch/patch)
```

I suspect it has to do with how we're compiling the rust binary for linux?

### PR DESCRIPTION
**Pull request by erikas-taroza**
## Description
Fixes #47 

This PR downgrades the version of the GitHub Actions Ubuntu machine. The machine will use an older version of glibc to build `patch` which will fix the error users are facing.

I have tested this change on an Ubuntu 20.04 VM.

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by eseidel** [comment]
So there is no way to build for and older glibc on a newer ubuntu with rust?

Crazy: https://kobzol.github.io/rust/ci/2021/05/07/building-rust-binaries-in-ci-that-work-with-older-glibc.html

**Comment by eseidel** [comment]
Oh, this would be easy for us to do: https://stackoverflow.com/questions/63724484/build-and-bind-against-older-libc-version

**Comment by eseidel** [comment]
https://github.com/shorebirdtech/updater/tree/main/patch is the source, btw.

**Comment by erikas-taroza** [comment]
> Oh, this would be easy for us to do: https://stackoverflow.com/questions/63724484/build-and-bind-against-older-libc-version

Agreed. I'll implement this in favor of my method.

**Comment by erikas-taroza** [comment]
Works on the Ubuntu VM and my machine (Fedora 38). However, the build time will be slightly longer because the `taiki-e/upload-rust-binary-action` action installs cargo cross.

**Comment by eseidel** [comment]
Looks reasonable to me.  @felangel knows GHA better than I do.

**Comment by aloRanking** [comment]
Hii, please when will this PR be merged? I'm currently facing this issue. Thanks.

**Comment by erikas-taroza** [comment]
> Hii, please when will this PR be merged? I'm currently facing this issue. Thanks.

@felangel needs to review the PR before it gets merged.

**Review by felangel — APPROVED** [review]

**Pull request merged**
